apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: marlon-echo-app 
  namespace: marlon-eks-activity 
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: echo-app 
  template: 
    metadata: 
      labels: 
        app: echo-app 
    spec: 
      containers: 
      - name: echo-container 
        image: hashicorp/http-echo 
        args: 
          - "-text=Hello, Marlon!" 
        ports: 
        - containerPort: 5678 