apiVersion: v1 
kind: Service 
metadata: 
  name: marlon-echo-service 
  namespace: marlon-eks-activity 
spec: 
  selector: 
    app: echo-app 
  ports: 
    - protocol: TCP 
      port: 80 
      targetPort: 5678